---
# tasks file for guest_provision

- name: "Start main guest_provision of '{{ vm.metadata.name }}'"
  set_fact:
    vm_conn:
      host: null

- name: init vm connection of
  include_tasks: init_vm_connection.yml

- name: Connect to VM
  include_tasks: connect_to_vm.yml

- name: "Add vm host to 'vms', '{{ vm.metadata.target_name}}' groups with variables"
  add_host:
    name: "{{ vm.metadata.name }}"
    groups:
    - vms 
    - "{{ vm.metadata.name }}"
    - "{{ vm.metadata.platform_name }}"
    - "{{ vm.metadata.target_name }}"
    
    # - "{{ vm.metadata.platform_name}}"
    ansible_connection: ssh 
    ansible_port: "22"
    ansible_host: "{{ vm_conn.host }}"

    ansible_user: "{{ vm.metadata.auth.user }}"
    ansible_password: "{{ vm.metadata.auth.password | default(omit, true) }}"
    ansible_become_method: "{{ vm.metadata.auth.become_method | default(omit, true) }}"
    ansible_become_user: "{{ vm.metadata.auth.become_user }}"
    ansible_become_password: "{{ vm.metadata.auth.become_password | default(omit, true) }}"

    # other host vars
    vm: "{{ vm }}"
    kvm_host: "{{ inventory_hostname }}"
