---
- name: "Wait DHCP leases for network '{{ network_name }}'"
  community.libvirt.virt_net:
    name: "{{ network_name }}"
    command: info
    uri: "{{ vm.metadata.connection | default(omit, true) }}"
  register: networks_info
  until: "networks_info is success"
  retries: 15
  delay: 2

- name: "DHCP leases of network '{{ network_name }}'"
  debug:
    msg: "{{ networks_info }}"
  
- name: "Find VM's dhcp lease"
  block:
  - name: "Find dhcp lease entry in network '{{ network_name }}'"
    include_tasks: getVMIPFromNetwork.yaml

  - name: "Update found ip in vm connection config"
    set_fact:
      vm_conn:
        ip: "{{ result.ip }}"
        hostname: "{{ result.hostname }}"
    when: network_name in networks_info.networks

  rescue:
  - name: "Lease not found on network {{ network_name }} "
    block:

    - name: "Fallback to find ip using neighbors"
      include_tasks: getVMIPFromNeighbor.yaml

    - name: "Update found ip in vm connection config"
      set_fact:
        vm_conn:
          ip: "{{ result.ip }}"

