
- name: Setup Proxy jump list
  vars:
    hostjumps: "{{ ( hostvars[ hostvars[ vm.metadata.name ].kvm_host ].hostjumps | default([]) ) + [ hostvars[ vm.metadata.name ].kvm_host ] }}"
  when:
    - hostvars[ vm.metadata.name ].kvm_host is defined
    - hostvars[ vm.metadata.name ].kvm_host in hostvars
  block:
      
    - name: Init Proxy jumps
      set_fact:
        proxyjumps: []
    
    - name: build needed ssh proxy hosts
      loop: "{{ hostjumps }}"
      loop_control:
        loop_var: node_name
      set_fact:
        proxyjumps: "{{ proxyjumps + [ jump ] }}"
      when: 
        - hostjumps | length > 0
        # Special case: we don't need a jump host if hostvars[ hostvars[ vm.metadata.name ].kvm_host ].ansible_connection == 'local'
        - hostvars[ node_name ].get('ansible_connection') | ternary( hostvars[ node_name ].get('ansible_connection') != 'local', true )
      vars:
        jump: "{{ [ [ hostvars[ node_name ].ansible_user, hostvars[ node_name ].ansible_host ] | join('@'), hostvars[ node_name ].ansible_port | default(22, true) | string ] | join( ':' ) }}"
      
    - debug:
        var: proxyjumps

    - name: Setup ProxyJumps
      when:
        - proxyjumps | length > 0
      add_host:
        name: "{{ vm.metadata.name }}"
        ansible_ssh_common_args: >
          -J {{ proxyjumps | join(',') }}
          -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
        hostjumps: "{{ hostjumps }}"
