
- name: Setup Proxy jump list
  vars:
    hostjumps: "{{ ( hostvars[ hostvars[ vm.metadata.name ].kvm_host ].hostjumps | default([]) ) + [ hostvars[ vm.metadata.name ].kvm_host ] }}"
  when:
    - hostvars[ vm.metadata.name ].kvm_host is defined
    - hostvars[ vm.metadata.name ].kvm_host in hostvars
  block:

    - name: Create temporary file for ssh host jumps
      ansible.builtin.tempfile:
        suffix: "ssh_{{ vm.metadata.name }}.cfg"
        state: file
      register: _tmp_ssh_cfg

    - name: template ssh config
      local_action:
        module: template
        src: ssh.cfg.j2
        dest: "{{ _tmp_ssh_cfg.path }}"    

    - name: Setup SSH config host inventory at
      add_host:
        name: "{{ vm.metadata.name }}"
        ansible_ssh_args: "-F {{ _tmp_ssh_cfg.path }}"
        hostjumps: "{{ hostjumps }}"
