---
roles:
  - name: stackhpc.libvirt-host
    version: 'v1.12.1'
collections:

---
collections:

  - name: community.general
    version: ">=3.5.0"
    type: galaxy
  
  - name: community.libvirt
    version: ">=1.2.0"
    type: galaxy

  - name: ansible.utils
    version: ">=2.7.0"
    type: galaxy

  - name: community.crypto
    version: ">=1.4.0"
    type: galaxy
