# params:
# - force: boolean if true will force to override the vm resources, otherwise will use cached resources if available. xml is updated on both cases
---

# - name: "Install Common Prerequisites"
#   include_tasks: install/install_shared.yml

- name: Run Virtual Machines lifecycle
  loop: "{{ virtual_machines }}"

  include_tasks: vm.yml
  
  loop_control:
    loop_var: vm