---
# tasks file for kvm_provision
- name: Ensure requirements in place
  package:
    name:
      - python3-libvirt
    state: present
  become: yes
- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no
- name: Create VM if not exists
  block:
  - name: Download, extract and verify image
    block:
    - name: Download base image
      get_url:
        url: "{{ resource_url }}"
        dest: "/tmp/{{ resource_name }}"
    - name: Unarchive if the downloaded resource is not the our image
      block:
        - name: unarchive with bunzip2
          shell: "bunzip2 -kf /tmp/{{ resource_name }}"
          when: resource_name is search('.bz2') and not(resource_name is search('tar.bz2'))
          register: unarchive_result
        - name: Un-archive with generic unarchive
          unarchive: 
            src: "/tmp/{{ resource_name }}"
            dest: "/tmp/"
          register: unarchive_result
          when: unarchive_result is skipped
      when: resource_name != image_name | bool
    - name: Get checksum of image
      stat:
        path: "/tmp/{{ image_name }}"
        checksum_algorithm: "{{ resource_checksum_type }}"
        get_checksum: yes
      register: shell_stat
    - name: "on Failed checksum"
      fail:
        msg: "Checksum mismatch"
      when: shell_stat.stat.checksum|string != resource_checksum_value
  - name: Copy base image to libvirt directory
    copy:
      dest: "{{ libvirt_pool_dir }}{{ image_name }}"
      src: "/tmp/{{ image_name}}"
      force: no
      remote_src: yes 
      mode: 0660
    register: copy_results
  - name: Configure the image
    command: |
      virt-customize -a {{ libvirt_pool_dir }}{{ image_name }} \
      --hostname {{ vm_name }} \
      --root-password password:{{ vm_root_pass }} \
      --ssh-inject 'root:file:{{ ssh_key }}' \
    when: copy_results is changed
  - name: Define vm
    community.libvirt.virt:
      command: define
      xml: "{{ lookup('template', 'target/' + vm_arch + '.xml.j2' ) }}"
  when: "vm_name not in existing_vms.list_vms"
- name: Ensure VM is started
  community.libvirt.virt:
    name: "{{ vm_name }}"
    state: running
  register: vm_start_results
  until: "vm_start_results is success"
  retries: 15
  delay: 2

- name: Ensure temporary files are deleted
  file:
    path: "{{ item }}"
    state: absent
  with_items: 
   - "/tmp/{{ resource_name }}"
   - "/tmp/{{ image_name }}"
  when: cleanup_tmp | bool
