---

# - name: "Install Common Prerequisites"
#   include_tasks: install/install_shared.yml

- name: Run Virtual Machines lifecycle
  loop: "{{ virtual_machines }}"

  include_tasks: vm.yml
  
  loop_control:
    loop_var: vm