---
- name: "VM Main lifecycle: {{ vm.metadata.name }}"
  debug:
    var: vm

- name: Install VM
  include_tasks: install/install_vm.yml

# - name : "Run VM"
#   include_role:
#     name: guest_provision