---
# vars:
#   target: The architecture / target
#   platform: The platform source file

- name: "Init VM - platform:'{{ platform }}', target:'{{ target }}'"
  debug:
    var: vm_definition

- name: "Load VM target vars for '{{ target }}'"
  include_tasks: load_target.yaml

- name: "Share arch_name alias with {{ platform }} vars"
  set_fact:
    arch_name: "{{ target_vars.vm.metadata.arch_name }}"
  
- name: "Load VM platform vars - {{ platform }}"
  include_tasks: load_platform.yaml

- name: Set vm template from definitions if defined
  ansible.utils.update_fact:
    updates:
    - path: platform_vars.vm.metadata.template
      value: "{{ vm_definition.template }}"
  when: vm_definition.template is defined

- name: "adding vm config"
  block:
  - name: "Fail if vm configs has not been loaded correctly"
    command: /bin/false
    when: not (target_vars.vm is defined and platform_vars.vm is defined )

  - name: Merge VM configuration for architecture and platform
    set_fact:
      a_vm: "{{ target_vars.vm | combine (platform_vars.vm, recursive=True) }}"
    
  - name: "Initialized VM - {{ a_vm.metadata.name }}"
    set_fact:
      virtual_machines: "{{ virtual_machines + [ a_vm ] }}"
