- name: Init permutation
  vars:
    permutation_list: "{{ permutations.platforms | default( [], true) | product( permutations.targets | default( [], true) ) | default( [] ) }}"
  block:
    - name: Serialize permutations to configurations
      loop: "{{ permutation_list }}"

      include_tasks: init/add_vm_config.yaml
      vars:
        configuration:
          target: "{{ pair[1] }}"
          platform: "{{ pair[0] }}"

      loop_control:
        loop_var: pair

