---

- name: "Include target tasks of '{{ target }}'"
  loop: "{{ lookup('first_found', params, errors='ignore', wantlist=True) }}"
  include_tasks:
    file: "{{ path }}"
  loop_control:
    loop_var: path 
  vars:
    params:
      files:
      - "{{ target }}.yaml"
      - "{{ target }}.yml"
      - default.yaml
      - default.yml
      paths:
      - "{{ ( parse_lookup_dir_path, 'targets' ) | path_join }}"
      - defaults/targets
      skip: True


- name: Merge VM definition with defaults
  set_fact:
    vm: "{{ default_vm_vars | combine (vm, recursive=True) }}"

- name: Save VM configuration for target
  set_fact:
    target_vars: "{{ vm }}"
