
- name: "include default platform vars of '{{ platform }}'"
  include_vars:
    file: "{{ item }}"
    name: default_platform_vars
  with_items: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
      - defaults.yml
      paths:
      - vars/platforms
      - defaults/platforms
      skip: True

- name: Set default platform_name
  ansible.utils.update_fact:
    updates:
    - path: default_platform_vars.vm.metadata.platform_name
      value: "{{ platform }}"
  when: not ( default_platform_vars.vm.metadata.platform_name is defined )

- name: "include platform vars of '{{ platform }}'"
  include_vars:
    file: "{{ item }}"
    name: custom_platform_vars
  with_items: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
      - "{{ platform }}.yml"
      paths:
      - vars/platforms
      - defaults/platforms
      skip: True
    target_vars: "{{ target_vars }}"

- name: Merge VM configuration for platform
  set_fact:
    platform_vars: "{{ default_platform_vars | combine (custom_platform_vars, recursive=True) }}"

- name: "Include platform tasks of '{{ platform }}'"
  include_tasks:
    file: "{{ item }}"
  with_items: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
      - "{{ platform }}.yml"
      - default.yaml
      paths:
      - tasks/platforms
      skip: True
