---

- name: "Debug"
  debug:
    msg: "{{permutations}}"
  
- name: "Setup permutations of targets and platforms"

  loop: "{{ permutations.platforms }}"

  include_tasks: permutate_targets.yaml
  
  loop_control:
    loop_var: platform
  when: permutations.platforms is defined