---

- name: Init dependencies
  set_fact:
    dependencies: []
  
- name: Setup dependencies
  block: 
  - name: include dependencies vars if defined
    include_vars:
      file: "{{ item }}"
    with_items: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
        - dependencies.yaml
        paths: "{{ ['vars'] | product( priority_import_paths ) | map('path_join') }}"
        skip: True
  
  - name: Install defined dependencies
    package:
      name: "{{ dependencies }}"
      state: present
    become: yes
    when: dependencies | length > 0
  
  - name: Include dependencies tasks
    include_tasks:
      file: "{{ item }}"
    with_items: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
        - dependencies.yaml
        paths: "{{ ['tasks'] | product( priority_import_paths ) | map('path_join') }}"
        skip: True
