---

- name: Setup dependencies
  block: 
  - name: Include dependencies tasks
    include_tasks:
      file: "{{ item }}"
    with_items: "{{ lookup('first_found', params) }}"
    vars:
      params:
        files:
        - dependencies.yaml
        paths: "{{ priority_import_paths }}"
        skip: True
