

- name: Deploys Dependencies based on Guest
  hosts: kvm_hosts
  tasks:

  - name: Loading vm definitions
    include_vars:
      file: vm_definitions.yaml
      name: define
    
  - name: Init virtual machines definitions
    include_role: 
      name: parse_vms_definitions
    vars:
      config: "{{ define }}"

  - name: Run Virtual Machines lifecycle
    loop: "{{ virtual_machines }}"

    include_role:
      name: guest_provision
    vars:
      vm: "{{ vm }}"
      should_add_vm: True
    
    loop_control:
      loop_var: vm

- name: "Start Guest Mains"
  hosts: vms
  tasks:
  - include_role:
      name: guest_provision
    vars:
      should_run_guest_main: True
    
      