

- name: Deploys Dependencies based on Guest
  hosts: localhost
  tasks:
  - name: Loading vm definitions
    include_vars:
      file: vm_definitions.yaml
      name: definitions
    
  - name: Init virtual machines definitions
    include_role: 
      name: parse_vms_definitions

  - name: Run Virtual Machines lifecycle
    loop: "{{ virtual_machines }}"

    include_role:
      name: guest_provision
    
    loop_control:
      loop_var: vm

- name: "Start Guest Mains"
  hosts: vms
  tasks:
    - include_tasks: roles/guest_provision/tasks/guest_main.yml
      