- name: Deploys VM based on Host arch
  hosts: kvm
  gather_facts: yes
  become: yes

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
        vars:
          architectures: [
            "{{ ansible_architecture }}"
          ]
          platforms: platforms

- name: Deploys VM based on arch to emulate on hosts
  hosts: x86_64
  gather_facts: yes
  become: yes
  
  tasks:
    - name: QEMU Provision role
      include_role:
        name: kvm_provision

        architectures: item.architectures
        platforms: item.platforms
      loop: 
        - {
            architectures: [
              "x86_64.yml",
              "arm.yml"
            ],
            platforms: platforms
        }

- name: 2 - Deploys VM based on arch to emulate on hosts
  hosts: x86_64
  gather_facts: yes
  become: yes
  
  tasks:
  
    
    - name: QEMU Provision role
      



      
      include_role:
        name: kvm_provision
        
        architectures: item.architectures
        platforms: item.platforms
      loop: 
        - {
            architectures: [
              "x86_64.yml",
              "arm.yml"
            ],
            platforms: platforms
        }
  
