- name: Deploys VM based on cloud image
  hosts: x8664_hosts
  gather_facts: yes
  become: yes

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
        vars_from: "target/{{ansible_architecture}}.yml"
        # vars_from: "target/aarch64.yml"
  
