all:
  hosts:
    L0-hypervisor:
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_connection: ssh
      ansible_host: localhost
      ansible_user: user
      ansible_become_method: enable
      hypervisor_group: user
      config:
        permutations:
          targets:
            - "amd64"
          platforms:
            - "debian_vs"
    VM debian_vs_amd64:
      ansible_ssh_private_key_file: ~/.ssh/id_ssh_rsa_vm
      ansible_host: localhost
      ansible_port: 2201
      ansible_user: user
      ansible_password: &pL1 virtualsquare
      ansible_become_user: root
      ansible_become_password: *pL1
      ansible_become_method: su
      # https://github.com/ansible/ansible/issues/15402
      # use kesy and Jump host to avoid using sshpass and a possibile 'escape of hell' by using nested ProxyCommand
      ansible_ssh_common_args: >
        -J {{ hostvars[ hostvars[ 'VM debian_vs_amd64' ].kvm_host ].ansible_user }}@{{ hostvars[ hostvars[ 'VM debian_vs_amd64' ].kvm_host ].ansible_host }}{{ ':' + (hostvars[ hostvars[ 'VM debian_vs_amd64' ].kvm_host ].ansible_port | default('22', true) | string) }}
        -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      kvm_host: L0-hypervisor
      config:
        permutations:
          targets:
            - "amd64"
          platforms: 
            - "debian_vs_vde"
    
    VM debian_vs_vde_amd64:
      ansible_ssh_private_key_file: ~/.ssh/id_ssh_rsa_vm
      ansible_host: localhost
      # Changed port to avoid Ansible jump loop error prevention (it shouldn't happen anyway)
      ansible_port: 2202
      ansible_user: user
      ansible_password: &pL2 virtualsquare
      ansible_become_user: root
      ansible_become_password: *pL2
      ansible_become_method: su
      ansible_ssh_common_args: >
        -J {{ hostvars[ hostvars[ hostvars[ 'VM debian_vs_vde_amd64' ].kvm_host ].kvm_host ].ansible_user }}@{{ hostvars[ hostvars[ hostvars[ 'VM debian_vs_vde_amd64' ].kvm_host ].kvm_host ].ansible_host }}{{ ':' + (hostvars[ hostvars[ hostvars[ 'VM debian_vs_vde_amd64' ].kvm_host ].kvm_host ].ansible_port | default('22', true) | string) }},{{ hostvars[ hostvars[ 'VM debian_vs_vde_amd64' ].kvm_host ].ansible_user }}@{{ hostvars[ hostvars[ 'VM debian_vs_vde_amd64' ].kvm_host ].ansible_host }}{{ ':' + (hostvars[ hostvars[ 'VM debian_vs_vde_amd64' ].kvm_host ].ansible_port | default('22', true) | string) }}
        -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      kvm_host: VM debian_vs_amd64
  children:
    hypervisors:
      hosts:
        L0-hypervisor:
  vars:
#   should_replace_vm: yes
#   ansible_ssh_args: "-F ./ssh.cfg"
    vde_network: vxvde://234.0.0.1
    

