
- name: Use defaults platform definition
  vars:
    vm_name: "VM {{ vm.metadata.platform_name }}_{{ vm.metadata.target_name }}"
  set_fact:
    vm:
      # metadata properties are used inside a task for installation and setup purposes
      metadata:
        name: "{{ vm_name }}"
        hostname: "vm.{{ vm.metadata.target_name }}.{{ vm.metadata.platform_name }}"
        connection: "{{ ansible_libvirt_uri | default('qemu:///session', true) }}"
        libvirt_pool_dir: "{{ ansible_env.HOME }}/.local/share/libvirt/images/"
        tmp_dir: "{{ ansible_env.HOME }}/tmp/"
        sources: [] 
      # Others properties are fully custom to templating a custom vm's xml

      # Some properties here, if needed, could override specific architecture values for all architectures
      vcpus: 4
      ram: 2048
      net:
        # type: network | bridge | vde | user
        type: user
        # source: default-net | virbr0 | /tmp/myswitch | hostfwd=..., hostfwd=..., ....
        source: "hostfwd=tcp:127.0.0.1:8022-:22"
        mac: "{{ '52:54:00' | random_mac( seed = vm_name ) }}"
        # ip used to reach this VM 
        ip: "127.0.0.1"
        mask: "24"

