- include_tasks: libvirt/get_capabilities.yaml
  when: libvirt_capabilities is not defined

- block:
    - import_tasks: fill_pool_with_config.yaml
  delegate_to: localhost
  delegate_facts: false
  vars:
    config: "{{ hostvars[ 'localhost' ].config }}"
  when: hostvars[ inventory_hostname ].libvirt_capabilities is defined
  run_once: true

- debug:
    var: configurations_pools
  run_once: true

- name: Dispatch pool entries per architecture
  loop: "{{ query('dict', configurations_pools, wantlist=true ) }}"
  vars:
    arch: "{{ pool_entries.key }}"
    pool: "{{ pool_entries.value}}"
    primary_domain: 'kvm'
    fallback_domain: 'qemu'
  loop_control:
    loop_var: pool_entries  
  include_tasks: dispatch_pool.yaml

- import_role:
    name: parse_vms_definitions

- name: init VM connection
  loop: "{{ virtual_machines }}"

  include_role:
    name: init_vm_connection
  
  loop_control:
    loop_var: vm

