    
- name: "Get vm ip"
  include_tasks: getVMIP.yml
  when: not isIP_static

- name: "Set connection info"
  block: 
  - name: "Set connection info"
    set_fact: 
      vm_conn:
        host: "{{ ((vm_conn.ip | default(vm_conn.hostname)) | default(vm.net.ip)) | default(vm.metadata.hostname) }}"
  - debug:
      msg: "VM host: '{{ vm_conn.host }}'"



