- name: Assert vm var is defined
  fail:
    msg: VM definition is not defined
  when: not ( vm is defined )

- name: "Start VM '{{ vm.metadata.name }}'"
  block:
  - name: "Ensure libvirt network is started"
    community.libvirt.virt_net:
      name: "{{ vm.net.source }}"
      state: active
      command: start
      uri: &libvirt_uri "{{ vm.metadata.connection | default(ansible_libvirt_uri, true) | default(omit, true) }}"
    when: vm.net is defined and vm.net.type == 'network'
  
  - import_tasks: startup.yaml
    when: ( "startup" in allowed_phases )
  
  delegate_to: "{{ kvm_host }}"

- name: VM Main lifecycle
  block:

  - import_tasks: wait_until_reachable.yaml

  - import_tasks: guest_main.yaml
    register: delegate_result

  rescue:

    - name: VM Main lifecycle failed
      debug: 
        var: fail_report
      vars:
        fail_report:
          failed_task: "{{ ansible_failed_task }}"
          failed_result: "{{ ansible_failed_result }}"
    
  always:
    - block:
        - import_tasks: shutdown.yaml
          when: ( "shutdown" in allowed_phases )
      delegate_to: "{{ kvm_host }}"
      
  