- name: Assert vm var is defined
  fail:
    msg: VM definition is not defined
  when: not ( vm is defined )

- name: "Start VM '{{ vm.metadata.name }}'"
  block:
  - name: "Ensure libvirt network is started"
    community.libvirt.virt_net:
      name: "{{ vm.net.source }}"
      state: active
      command: start
      uri: &libvirt_uri "{{ vm.metadata.connection | default(ansible_libvirt_uri, true) | default(omit, true) }}"
    when: vm.net is defined and vm.net.type == 'network'
  
  - name: Ensure VM is started
    community.libvirt.virt:
      name: "{{ vm.metadata.name }}"
      state: running
      uri: *libvirt_uri
    register: vm_start_result

    until: vm_start_result is success
    retries: "{{ retry_count | default(10) }}"
    delay: "{{ retry_delay | default(5) }}"
  
  delegate_to: "{{ kvm_host }}"

# - name: "debug host vars"
#  debug:
#    var: hostvars[ vm.metadata.name ]

- name: VM Main lifecycle
  block:
  - name: Wait for defined connection to VM
    wait_for_connection:
    when: ansible_connection is defined
    register: connection_wait_result
  
  - name: Wait until VM becomes reachable
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ ansible_port | default( 22 ) }}"
      timeout: "{{ connection_timeout | default(120) }}"
    when: not ( ansible_connection is defined )
    register: connection_wait_result

  - include_tasks: guest_main.yaml
    register: delegate_result

  rescue:
  - name: on wait connection error - report
    debug: 
      var: connection_wait_result
    when: connection_wait_result is failed
  - name: on VM connection error - report
    debug: 
      var: delegate_result
    when: delegate_result is failed
  always:
  - name: Stopping VM
    community.libvirt.virt:
      command: shutdown
      name: "{{ vm.metadata.name }}"
      state: shutdown
      uri: *libvirt_uri
    delegate_to: "{{ kvm_host }}"
    register: vm_stop_result
    until: vm_stop_result is success
    retries: "{{ retry_count | default(10) }}"
    delay: "{{ retry_delay | default(5) }}"
  