
- name: Restore Clean
  when:
    - snapshot_phase_name.clean in snapshot_list
    - ( 'restore clean' in allowed_phases )
  block:
  
    - block:

        - name: Restore Clean Snapshot
          vars:
            snapshot_name: "{{ snapshot_phase_name.clean }}"
          import_role: 
            name: libvirt_snapshot
            tasks_from: restore

          # ignore any error like "snaphot unsupported" or "snapshot already exists / doesn't exists"
          failed_when: false
        
        - name: get snapshot result
          shell: /bin/true
          register: restore_clean_result
          # is skipped when rc != 0 
          when: &on_success 
            - snapshot_restore_result is defined
            - not( snapshot_restore_result is skipped )
            - snapshot_restore_result.rc == 0
          # is changed when rc == 0
          changed_when: *on_success
      
      delegate_to: "{{ kvm_host }}"

    - include_tasks: wait_until_reachable.yaml
      when: snapshot_type == 'external'
