# vars:
#   vm_name: "Vm name"
#   snapshot_name: "snapshot name"
#   uri: "session uri"  example: qemu:///system
---

- name: listing snapshots
  import_tasks: snapshot_list.yaml
- name: "Create snapshot for vm '{{ vm_name }}' as '{{ snapshot_name }}'"
  shell: 
    cmd: >-
      virsh
      --connect {{ uri | quote }}
      snapshot-create-as
      --domain {{ vm_name | quote }}
      --name {{ snapshot_name | quote }}
  when: not ( snapshot_name in snapshot_list )
  
        