all:
  children:
    Arch-Linux:
      vars:
        # arch image doesn't have python installed, so use ssh port-based waits instead
        wait_until_port_reachable: true
    hypervisors:
      hosts:
        local_hypervisor:
          ansible_connection: local
          ansible_host: localhost
      vars:
        config:
          permutations:
            targets:
              - "amd64"
            platforms:
              - "debian_vs"
              - "Arch-Linux"
    # reuse same port of previous examples
    debian_vs:
      hosts:
        VM debian_vs_amd64:
      vars:
        ansible_port: 2201
    vms:
      vars:
        should_setup_proxy_jumps: false
        allowed_phases:
          - startup
          - restore init
          - create init
          - restore clean
          - create clean
          - dependencies
          - init
          - main
          - terminate
          - shutdown