
- include_tasks: "{{ (phases_lookup_dir_path, 'common-tasks', 'gather_sysinfo.yaml' ) | path_join }}"

- block:

    - include_tasks: "{{ (phases_lookup_dir_path, 'common-tasks', 'sync-clock.yaml' ) | path_join }}"

    - include_vars:
        file: "{{ (phases_lookup_dir_path, 'dependencies', ansible_distribution + '.yaml' ) | path_join }}"
    
    - name: Update manager cache
      package:
        update_cache: yes
        upgrade: yes

    - name: Install dependencies.
      package:
        name: "{{ dependencies }}"
        state: latest

    - name: Reboot VM
      ansible.builtin.reboot:
        connect_timeout: "{{ connection_timeout | default(omit, true) }}"
        test_command: 'true'

  become: yes

- name: Clone repo
  ansible.builtin.git:
    repo: 'https://github.com/jjak0b/ansible_farm.git'
    dest: &prj_dir ~/ansible_farm
    version: master
    recursive: true
  
- name: Install collections and roles together
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: ~/ansible_farm/requirements.yml
  retries: 4
  delay: 2
  register: install_repo_requirements_result
  until: install_repo_requirements_result is success
