---
- name: Install common System components
  package:
    name:
      # community.libvirt.virt
      - python3-libvirt
      # community.libvirt.virt_net
      - python3-lxml
      # use password on ssh vm connections 
      - sshpass
    state: present
  become: yes

- name: ensure libvirt group exists
  group:
    name: libvirt
    state: present
  become: yes

- name: "add {{ ansible_env.USER }} to libvirt group"
  user:
    name: "{{ ansible_env.USER }}"
    groups: libvirt
    append: yes
