# VM Directory 
# - name: Ensure images directory exists 
#  file:
#    state: directory
#    path: &images_dir "{{ vm.metadata.libvirt_pool_dir }}"
#   owner: root
#    group: libvirt
#    mode: u+rwx,g+rwx,o+rwx

- name: Ensure images directory exists and own to libvirt-qemu
  file:
    path: "{{ vm.metadata.libvirt_pool_dir }}" 
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: libvirt-qemu
    mode: u+rwx,g+rwx,o+rx
  become: True
  
- name: Fetch and install required resources

  loop: "{{ vm.metadata.sources }}"

  include_tasks: install_resource.yml
  
  loop_control:
    loop_var: source
