
- name: Ensure tmp directory exists
  file:
    path: "{{ vm.metadata.tmp_dir }}" 
    state: directory

- name: Fetch and install required resources

  loop: "{{ vm.metadata.sources }}"

  include_tasks: install_resource.yml
  
  loop_control:
    index_var: source_index
    loop_var: source
