
- name: Setup metadata

  include_tasks: "install_metadata.yml"

- name: Search for VM template

  vars:
    file_list:
      - "{{ vm.metadata.name }}.xml.j2"
      - "{{ vm.arch }}.xml.j2"
      - default.xml.j2
    params:
      files: "{{ [ vm.metadata.template + '.xml.j2' ] + file_list if vm.metadata.template is defined else file_list }}"
      paths:
      - "{{ ( parse_lookup_dir_path, 'templates' ) | path_join }}"
      - defaults/templates
  set_fact:
    vm_xml: "{{ lookup('first_found', params ) }}"

- name: "Define VM using {{ vm_xml }}"
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', vm_xml ) }}"
    uri: "{{ vm.metadata.connection | default(omit, true) }}"

- name: Ensure temporary files are deleted
  file:
    path: "{{ vm.metadata.libvirt_pool_dir }}{{ item.source.resource_name }}"
    state: absent
  with_items: 
   - "{{ vm.metadata.sources }}"
  when: vm.metadata.cleanup_tmp | bool
