
---

- name: "Including callback {{ callback_task_file }}"
  vars:
    _searchCallbackParams:
      files:
        - "{{ callback_task_file }}"
      paths:
        - "{{ ( hypervisor_lookup_dir_path ) | path_join }}"
        - tasks
      skip: true
  loop: "{{ query('first_found', _searchCallbackParams, errors='ignore') }}"

  include_tasks:
    file: "{{ callback_filepath }}"

  loop_control:
    loop_var: callback_filepath 
  
  
