
---

- name: "Including callback {{ callback_task_file }}"
  vars:
    params:
      files:
        - "{{ callback_task_file }}"
      paths:
        - "{{ ( hypervisor_lookup_dir_path ) | path_join }}"
        - tasks
      skip: true
  loop: "{{ lookup('first_found', params, errors='ignore', wantlist=True) }}"

  include_tasks:
    file: "{{ callback_filepath }}"

  loop_control:
    loop_var: callback_filepath 
  
  
