---

- name: Init vms vars list
  set_fact:
    virtual_machines: []
    permutations: "{{ config.permutations | default(omit, true) }}"
    definitions: "{{ config.definitions | default([] ) }}"

- name: Init permutations
  include_tasks: init/init_permutations.yaml
  when: permutations is defined

- name: Normalize definitions list
  set_fact:
    definitions: "{{ definitions | unique }}"

- name: "Init all vms of definitions list"

  loop: "{{ definitions }}"

  include_tasks: init/init_vm.yaml
  vars:
    platform: "{{ vm_definition.platform }}"
    target: "{{ vm_definition.target }}"

  loop_control:
    loop_var: vm_definition
  when: definitions is defined