---

- name: Init vms vars list
  set_fact:
    virtual_machines: []
    configurations: "{{ config.list | default([] ) }}"

- name: Serialize Permutation
  block:
    - name: Init permutations
      import_tasks: init/init_permutations.yaml
  vars:
    permutations: "{{ config.permutations | default(omit, true) }}"
  when: permutations is defined

- name: Normalize definitions list
  set_fact:
    configurations: "{{ configurations | unique }}"

- name: "Init all vms of definitions list"

  loop: "{{ configurations }}"

  include_tasks: init/init_vm.yaml
  vars:
    platform: "{{ configuration.platform }}"
    target: "{{ configuration.target }}"

  loop_control:
    loop_var: configuration
  when: configurations is defined