# vars:
#   vm_name: "Vm name"
#   snapshot_name: "snapshot name"
#   uri: "session uri"  example: qemu:///system
---

- name: Delete internal snapshot
  block:
    - name: "Delete internal snapshot: '{{ snapshot_name }}'"
      shell: 
        cmd: >-
          virsh
          --connect {{ uri | quote }}
          snapshot-delete
          --domain {{ vm_name | quote }}
          --snapshotname {{ snapshot_name | quote }}
          --children
      register: snapshot_delete_internal_result
      when:
        - snapshot_type == 'internal'

      # Note aboute external snapshots: This is a very recent feature for external snapshots since it's available from 9.0.0, see https://libvirt.org/news.html#v9-0-0-2023-01-16
      # BUT they behave differently than internal snapshots, so going to delete them manually
    - name: "Delete external snapshot: '{{ snapshot_name }}'"
      include_tasks: delete_external.yaml
      when:
        - snapshot_type == 'external'

- name: set snapshot result
  set_fact:
    snapshot_delete_result: "{{ snapshot_delete_internal_result is skipped | ternary( snapshot_delete_external_result, snapshot_delete_internal_result ) | default( snapshot_delete_internal_result ) }}"
