# Store snapshot names available for the specified VM into snapshot_list fact
# vars:
#   vm_name: "Vm name"
#   snapshot_name: "snapshot name"
#   uri: "session uri"  example: qemu:///system
---
# - name: Ensure snapshot is hasn't been created
  
- block:
  - name: "Get snapshots for vm '{{ vm_name }}'"
    shell: 
      cmd: >-
        virsh
        --connect {{ uri | quote }}
        snapshot-list
        --domain {{ vm_name | quote }}
        --parent
        {% if snapshot_type == 'internal' %}
        --internal
        {% else %}
        --external
        {% endif %}
    register: snapshot_list_result
    # skip header, split words by whitespaces, and collect values in "Name" column
  - name: List snapshot names
    vars:
      line_pattern: "(\\s+)(?P<name>\\S+)(\\s+)(.+)"
    set_fact:
      snapshot_list: "{{ [] if (snapshot_list_result.stdout_lines | length <= 2)
                            else (snapshot_list_result.stdout_lines[2:] | map( 'regex_search', line_pattern, '\\g<name>' ) | map( 'first' ) | list) }}"    
  rescue:
    - set_fact:
        snapshot_list: []

  