# vars:
#   vm_name: "Vm name"
#   snapshot_name: "snapshot name"
#   uri: "session uri"  example: qemu:///system
---

- name: "Restore internal snapshot ({{ snapshot_name }})"
  include_tasks: restore_internal.yaml
  when: snapshot_type == 'internal'

# Simulate a snapshot-edit --current and update the VM xml
- name: "Restore external snapshot ({{ snapshot_name }})"
  include_tasks: restore_external.yaml
  when: snapshot_type == 'external'

