# Store snapshot names available for the specified VM into snapshot_list fact
# vars:
#   vm_name: "Vm name"
#   snapshot_name: "snapshot name"
#   uri: "session uri"  example: qemu:///system
---
# - name: Ensure snapshot is hasn't been created
  
- block:
  - name: "Get snapshots for vm '{{ vm_name }}'"
    shell: 
      cmd: >-
        virsh
        --connect {{ uri | quote }}
        snapshot-list
        --domain {{ vm_name | quote }}
    register: list_result
    # skip header, split words by whitespaces, and collect values in "Name" column
  - name: List snapshot names
    set_fact:
      snapshot_list: "{{ [] if (list_result.stdout_lines | length <= 2)
                            else (list_result.stdout_lines[2:] | map( 'split' ) | map( 'first' ) | list) }}"    
  rescue:
    - set_fact:
        snapshot_list: []

  