
vm:
  # metadata properties are used inside a task for installation and setup purposes
  metadata:
    name: &vm_name "VM {{ arch_name }}"
    hostname: *vm_name
    connection: "qemu:///system"
    libvirt_pool_dir: "/var/lib/libvirt/images/"
  # connection: "qemu:///session" 
  # libvirt_pool_dir: "{{ansible_env.HOME}}/.local/share/libvirt/images/"
    auth:
      become_user: &root_user "root"
      become_password: &root_pass ""
    # become_method: "su"
      user: *root_user
      password: *root_pass
      root_pass: *root_pass
    # TODO 
      ssh_key: "{{ansible_env.HOME}}/.ssh/id_rsa.pub"
    sources:
    - uri: "myURI/myImage-{{ arch_name }}.qcow2.tar.gz"
      checksum_uri: "myURI/myImage.qcow2.tar.gz.sha1sum"
      checksum_type: "sha1"
      # fallback checksum value
      checksum_value: "onlyThisIsSupported"
      # image name unarchived / processed
      unarchived: &image_file_name "myImage.qcow2"
    cleanup_tmp: no
  # Others properties are fully custom to templating a custom vm's xml

  # Some properties here, if needed, could override specific architecture values for all architectures
  vcpus: 4
  ram: 2048
  net:
    # type: network
    # type: bridge
    type: user
    source: default
    # source: virbr0
    mac: "52:54:00:ca:cc:ac"
    ip: "192.168.100.1"
    mask: "24"
  disks:
  - type: "raw"
    devname: "hda"
    src: *image_file_name

