# This playbook can use all variables from parse_vms_definitions and init_vm_connection roles defined on each hypervisor's specific inventory
---

- name: Init VM on Hypervisor
  hosts: "{{ hypervisors_group | default('hypervisors') }}"
  gather_facts: yes
  roles:
    - jjak0b.ansible_farm.parse_vms_definitions
  tasks:  

    - name: init VM connection
      loop: "{{ virtual_machines }}"

      include_role:
        name: jjak0b.ansible_farm.init_vm_connection
      
      loop_control:
        loop_var: vm
