
---

- name: VM provisioning on Hypervisor host
  hosts: "{{ vms_group | default('vms') }}"
  gather_facts: no
  serial: 1
  tasks:

    - block:
      
        - name: gather min facts of hypervisor host since some definitions require to use them
          setup:
            gather_subset: 
            - '!all'
        
        - name: "start KVM Provision role for '{{ vm.metadata.name }}'"
          include_role: 
            name: jjak0b.ansible_farm.kvm_provision
        
      delegate_to: "{{ kvm_host }}"
      
      tags:
        - kvm_provision

    - block:

        - name: "Start VM provisioning of '{{ vm.metadata.name }}' "
          include_role: 
            name: jjak0b.ansible_farm.guest_provision
        
        - name: Flag VM as processed
          add_host:
            name: "{{ inventory_hostname }}"
            groups:
              - processed
      tags:
        - guest_provision
