all:
  children:
    hypervisors:
      hosts:
        local_hypervisor:
          ansible_connection: local
          ansible_host: localhost
      vars:
        config:
          permutations:
            targets:
              - "amd64"
            platforms:
              - "vm-as-hypervisor"

