all:
  hosts:
    L0-hypervisor:
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_connection: ssh
      ansible_host: localhost
      ansible_user: user
      ansible_become_method: enable
      config:
        permutations:
          targets:
            - "amd64"
          platforms:
            - "debian_vs"
#            - "macOS_BigSur"
    VM debian_vs_amd64:
      ansible_connection: ssh
      ansible_port: 2201
    VM macOS_BigSur_amd64:
      ansible_connection: ssh
      ansible_port: 2202
  children:
    hypervisors:
      hosts:
        L0-hypervisor:
    require_setup:
      hosts:
        VM macOS_BigSur_amd64:

    