all:
  hosts:
    L0-hypervisor:
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_connection: ssh
      ansible_host: localhost
      ansible_user: user
      ansible_become_method: enable
      config:
        permutations:
          targets:
            - "amd64"
          platforms:
            - "macOS-setup.yaml"
    VM macOS-setup-big-sur_amd64:
      ansible_user: user
      ansible_password: userpassword
      ansible_port: 2201
  children:
    hypervisors:
      hosts:
        L0-hypervisor:

    