
- name: Run openwrt edit image
  vars:
    image_path: "{{ (vm.metadata.libvirt_pool_dir, vm.disks[0].src ) | path_join }}"
    image_type: "{{ vm.disks[0].type }}"
    initscript_filename: S99firstboot
    file_src: /tmp/S99firstboot
  block:

  - name: d
    debug:
      var: vm
  
  - name: template initscript and send it to hypervisor
    template:
      src: openwrt-init-script.sh.j2
      dest: "{{ file_src }}"
    
  - name: "Configure the image with initscript into {{ image_path }}"
    command: |
      virt-customize 
      --format {{ image_type }} -a {{ image_path | quote }} \
      --copy-in {{ file_src }}:/etc/rc.d \
      --chmod 0755:/etc/rc.d/"{{ initscript_filename }}"
# - name: Remove initscript from hypervisor
#   file:
#       path: *file_path
#       state: absent

