
- name: check if backup exists
  stat:
    path: &backup_filepath "{{ (vm.metadata.tmp_dir, 'backup_' + source.asset_name ) | path_join }}" 
    follow: yes
  register: backup_stat_result

- name: Create backup of asset
  copy:
    src: &asset_filepath "{{ (vm.metadata.tmp_dir, source.asset_name ) | path_join }}"
    dest: *backup_filepath
    remote_src: yes
  when: not backup_stat_result.stat.exists

- name: Replace asset in tmp dir with backup
  copy:
    src: *backup_filepath
    dest: *asset_filepath
    remote_src: yes
    force: yes