- name: Fix libguestfs permission issue on Ubuntu
  block:
    # source: https://manpages.ubuntu.com/manpages/bionic/man1/guestfs-faq.1.html#downloading,%20installing,%20compiling%20libguestfs  

    - name: Get kernel access permission
      stat:
        path: /boot/vmlinuz
        follow: yes
      register: kernel_stat_result
      failed_when: false

    - name: Fix kernel access permission if we are in Ubuntu
      shell: chmod 0644 /boot/vmlinuz*
      become: yes
      when: not kernel_stat_result.stat.readable

  when: ansible_distribution == "Ubuntu"

- name: Setup SSH on image
  shell:
    chdir: "{{ (vm.metadata.tmp_dir, source.asset_name | dirname ) | path_join }}"
    cmd: >
      virt-customize -a {{ source.asset_name + '_tmp' }}
      --firstboot-command 'systemctl stop sshd.service'
      --firstboot-command 'systemctl enable sshd.service'
      --firstboot-command 'systemctl start sshd.service'
      --firstboot-command 'sshd -t'
  when: false


