---

permutations:
  targets:
    - "amd64"
  platforms:
    - "debian_vs"
#   - "debian_vs_new"

list: [] 
# - platform: "debian_vs.yml"
#   target: "amd64"
# - platform: "debian_sid.yml"
#   target: "arm64"
# - platform: "openwrt_arm64.yml"
#   target: "armvirt"
#   template: "virtio"

  
