ansible_user: user
ansible_password: virtualsquare
ansible_become_user: root
ansible_become_password: virtualsquare
ansible_become_method: su
# NOTE: You SHOULD use https://docs.ansible.com/ansible/latest/user_guide/vault.html
